### ISSUE TITLE
Замечания по FindText

### ISSUE THREAD

**Issue by oMystique** [ilyarom/OOP-Projects#1]
- Необходимо добавить в .gitignor продукты сборки c++ проектов. Пример - https://github.com/alexey-malov/oop/blob/master/.gitignore
- Так же, необходимо следить за тем, чтобы в процессе сборки не было предупреждений. В вашей программе предупреждения есть.
  ![warnings in program](https://cloud.githubusercontent.com/assets/14878773/18410437/dbdee558-776b-11e6-80a7-3f9c60f2e8f5.png)
  Рекомендуется использовать 4 уровень предупреждений. О том, как его использовать:
  ![warning_level](https://cloud.githubusercontent.com/assets/14878773/18410443/f16a2bb2-776b-11e6-9876-ad31bec19305.png)
- Что касается кода:

``` c++
    ifstream file(argv[1]);
    if (!file.good())
    {
        cout << "Некорректно введены входные данные, сначала указывается имя файла, далее через пробел строка, которую нужно найти" << "\n";
        return 1;
    }
```

Для проверки успешности открытия файла лучше использовать `file.is_open()`. Так же, из текста сообщения не совсем понятно в чём конкретно проблема. Лучше явно написать о том, что, к сожалению, невозможно открыть файл и уже затем напечатать подсказку.
- Этот велосипед можно заменить методом `find` std::string

``` c++
for (int j = 0; j < line.length(); ++j)
        {
            if (line[j] == strToFind[i])
            {
                ++i;
                if (i == strToFind.length())
                {
                    cout << currentLine << "\n";
                    strFinded = true;
                }
            }
            else
            {
                i = 0;
            }
        }
```

Примеры использования можно найти тут: http://www.cplusplus.com/reference/string/string/find/

*

``` c++
    string strToFind = string(argv[2]);
```

 В данном случае не стоит явно отправлять массив char-ов в конструктор std::string и затем присваивать сконструированный объект. С задачей присваивания вполне может справиться стандартный оператор присваивания std::string

``` c++
    string strToFind = argv[2];
```
- Лучше опять же более конкретно описать ошибку, и затем напечатать подсказку

``` c++
    if (strToFind.length() == 0)
    {
        cout << "Некорректно введены входные данные, сначала указывается имя файла, далее через пробел строка, которую нужно найти" << "\n";
        return 1;
    }
```

И опять же, вместо явной проверки строки на пустоту  `strToFind.length() == 0` можно использовать конструкция `strToFind.empty()`.
- "В комплекте с программой должны обязательно поставляться файлы, позволяющие проверить корректность её работы в автоматическом режиме." 
  Пример можно найти тут: https://github.com/alexey-malov/oop/tree/master/labs/lab1/CopyFile
- Да, и в данном случае, программа работает не корректно (не находит "Евгения Онегина" в строке `Евгений Евгений Онегин.`

![default](https://cloud.githubusercontent.com/assets/14878773/18410756/77a6e20a-7772-11e6-9c2b-73dfa36b21cc.png)

Пока **k=0**.

**Comment by ilyarom** [comment]
Здравствуйте. Большое спасибо за пояснения и указания на ошибки.
По ходу исправления их возник вопрос по gitignore. Не совсем разобрался с
тем, что нужно добавить туда.
Касательно же других ошибок, все исправил.
Создал каталог Tests где находятся 4 текстовых файла для тестирования.

10 сентября 2016 г., 16:18 пользователь Alexey Ildarkin <
notifications@github.com> написал:

**Comment by ilyarom** [comment]
А нет, не исправил. Не сделал bat файл. Прошу прощения.

10 сентября 2016 г., 20:01 пользователь Илья - ilyarom5@gmail.com написал:

**Comment by oMystique** [comment]
`.gitignore` позволяет настроить автоматическое игнорирование файлов/папок, чтобы не загружать на сервер продукты сборки проекта, например файлы, с расширением *.sdf, *.opensdf, *.tlog, *.ipch, *.pdb и т.д и т.п
Правильный гитигнор для VisualStudio можно найти в репозитории у Алексея Малова и присвоить себе :)
https://github.com/alexey-malov/oop/blob/master/.gitignore
Либо же, в официальном репозитории github - https://github.com/github/gitignore/blob/master/VisualStudio.gitignore
Документация по .gitignore - https://git-scm.com/docs/gitignore

P.S Не забудьте запушить изменения =)

**Comment by ilyarom** [comment]
Сделано.
Вчера вечером сидел над bat файлом и разбирался с кодом, который показан у
Алексея Малова.
Возникли трудности. Не могу понять код чтобы написать свой тестовый bat
файл.
Не могли бы вы помочь, пожалуйста?

10 сентября 2016 г., 20:10 пользователь Alexey Ildarkin <
notifications@github.com> написал:

**Comment by oMystique** [comment]
Вот фрагмент кода *.bat файла с тестами, позаимствованный из репозитория А. Малова. Добавил немного комментариев.

``` c++
rem проверяем копирование пустого файла
rem запускаем программу (переменная PROGRAM означает первый аргумент командной строки (путь до *.exe))
rem empty.txt - путь до входного файла; %TEMP%\empty.txt - путь до выходного файла, где %TEMP% - переменная окружения (путь до папки temp)
%PROGRAM% empty.txt %TEMP%\empty.txt
rem если программа завершила свою работу с кодом возврата 1 (что не ожидалось), то отправляемся в точку err.
if ERRORLEVEL 1 goto err
rem выполняем сравнение выходного файла и файла с ожидаемым результатом
fc.exe %TEMP%\empty.txt empty.txt
rem аналогично, если, код возврата равен 1, то отправляемся в err
if ERRORLEVEL 1 goto err
```

**Comment by ilyarom** [comment]
Сделано! bat файл и тестовые данные лежат в директории Debug вместе с exe
файлом. Спасибо.

12 сентября 2016 г., 10:15 пользователь Alexey Ildarkin <
notifications@github.com> написал:

**Comment by oMystique** [comment]
Нужно запушить изменения на сервер =)
![last commit](https://cloud.githubusercontent.com/assets/14878773/18529443/bad9c842-7ad5-11e6-98c5-372df5f4e1e6.png)

**Comment by ilyarom** [comment]
Ахах, запушил)
flipbyte пока не готов. Не сделал тесты

2016-09-14 23:48 GMT+03:00 Alexey Ildarkin notifications@github.com:

**Comment by oMystique** [comment]
``` c++
int strPosition;
```
- Для хранения индекса элемента строки следует использовать беззнаковый тип `size_t`.  И сравнение с `-1` можно с лёгкостью заменить на сравнение с `string::npos`
  Ну а на самом деле, в данном случае нет смысла сохранять индекс элемента, ведь это

``` c++
while (getline(file, line))
    {
        strPosition = line.find(strToFind);
        if (strPosition != -1)
        {
            cout << currentLine << "\n";
            strFinded = true;
        }
        ++currentLine;
    };
```

легко может преобразоваться в это:

``` c++
while (getline(file, line))
    {
        if (line.find(strToFind) != string::npos)
        {
            cout << currentLine << "\n";
            strFinded = true;
        }
        ++currentLine;
    };
```
- Вместо `"\n"` можно использовать `std::endl;`
- В репозитории отсутствует bat-файл с тестами и, в виду этого обстоятельства, пока **k=0.5**

**Comment by ilyarom** [comment]
Добавил тестовые файлы. Разместил в директории с cpp файлов. Не уверен на
счет кодировки. Возился с кодировкой чтобы можно было работать в
FarManager.
Делал файлы в кодировке ANSI и OEM. test.bat был в ANSI. russiantest.txt в
OEM.
На счет кода - все исправил.
На паре нам говорили про std::endl; Сказали что разницы особо нет но лучше
использовать "\n".
Или же нужно исправить на endl?

16 сентября 2016 г., 14:36 пользователь Alexey Ildarkin <
notifications@github.com> написал:

**Comment by ilyarom** [comment]
Доделал flipbyte.

16 сентября 2016 г., 16:40 пользователь Илья - ilyarom5@gmail.com написал:

**Comment by ilyarom** [comment]
Выложил доп.задание rle.

17 сентября 2016 г., 12:12 пользователь Илья - ilyarom5@gmail.com написал:

**Comment by oMystique** [comment]
- [ ] Следует выпилить из репозитория продукты сборки C++ проектов
- [ ] Можно выполнить небольшие преобразования над

``` c++
    bool strFinded = FindLines(file, strToFind);
    if (!strFinded)
    {
        cout << "Text not found" << "\n";
    }
```

и превратить это в:

```
    if (!FindLines(file, strToFind))
    {
        cout << "Text not found" << "\n";
    }
```
- [ ]  Хорошо бы запускать тесты в рамках `PostBuildEvent`
  https://github.com/alexey-malov/oop/wiki/%D0%9F%D0%BE%D1%8F%D1%81%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F-%D0%BF%D0%BE-1-%D0%BB%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%BE%D0%B9-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B5
- [ ] Не стоит явно указывать путь к *.exe файлу программы в тестах.

``` bash
set PROGRAM="../Debug/FindText.exe"
```

Пример корректного написания автоматических bat-тестов можно найти в репозитории у А. Малова
- [ ] Стоит запилить константу для магического числа `if (argc != 3)`

**k = 0.91**
